#!/bin/bash
#PBS -l walltime=96:00:00
#PBS -l nodes=1:ppn=2
#PBS -j oe
 
Location_DIR=/scratch/speng/projects/Mouse_Xeno/fastqDir/PDX_Columbia/fastq/PDX_Columbia_Xenome_Output
cd ${Location_DIR}

echo "Start fastq Process"

cat ${FILENAME}*_human_1.fastq ${FILENAME}*_both_1.fastq|awk '{if (NR % 4 == 1) print "@"$0; else if (NR % 4 == 3) print "+"$0; else print $0}'|gzip > ${READ1}

cat ${FILENAME}*_human_2.fastq ${FILENAME}*_both_2.fastq|awk '{if (NR % 4 == 1) print "@"$0; else if (NR % 4 == 3) print "+"$0; else print $0}'|gzip > ${READ2}
	
echo "End fastq Process"
